my-bigquery-db:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: chicago-assessment
      dataset: gold
      threads: 4 
      keyfile: /Users/ddafaallah/Desktop/research_v2/dbt/chicago-silver/chicago-assessment-e6cd85f68d50.json
      OPTIONAL_CONFIG: VALUE
