name: dbt_run_schedule

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_dbt:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-bigquery

    - name: Setup GCP credentials
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        create_credentials_file: true

    - name: Set GOOGLE_APPLICATION_CREDENTIALS
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ steps.auth.outputs.credentials_file }}" >> $GITHUB_ENV

    - name: Run DBT models for silver
      working-directory: ./chicago-silver
      run: |
        dbt run --target prod
    
    - name: Run DBT models for gold
      working-directory: ./chicago-gold
      run: |
        dbt run --target prod
