name: dbt_run_schedule

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_dbt:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-bigquery

    - name: Setup GCP credentials
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Run DBT models for silver
      run: |
        dbt run --profiles-dir ./chicago-silver --target prod

    - name: Run DBT models for gold
      run: |
        dbt run --profiles-dir ./chicago-gold --target prod
