name: dbt_run_schedule

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_dbt:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-core dbt-bigquery

    - name: Setup GCP credentials
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        create_credentials_file: true

    - name: Capture GCP credentials file path
      run: echo "CREDENTIALS_FILE_PATH=${{ steps.auth.outputs.credentials_file }}" >> $GITHUB_ENV

    - name: Create DBT profiles.yml for silver
      working-directory: ./chicago-silver
      run: |
        echo "chicago_profile:" > profiles.yml
        echo "  target: dev" >> profiles.yml
        echo "  outputs:" >> profiles.yml
        echo "    dev:" >> profiles.yml
        echo "      type: bigquery" >> profiles.yml
        echo "      method: service-account" >> profiles.yml
        echo "      project: your-gcp-project-id" >> profiles.yml
        echo "      dataset: silver" >> profiles.yml
        echo "      threads: 4" >> profiles.yml
        echo "      keyfile: '${{ env.CREDENTIALS_FILE_PATH }}'" >> profiles.yml

    - name: Create DBT profiles.yml for gold
      working-directory: ./chicago-gold
      run: |
        echo "chicago_profile:" > profiles.yml
        echo "  target: prod" >> profiles.yml
        echo "  outputs:" >> profiles.yml
        echo "    prod:" >> profiles.yml
        echo "      type: bigquery" >> profiles.yml
        echo "      method: service-account" >> profiles.yml
        echo "      project: your-gcp-project-id" >> profiles.yml
        echo "      dataset: gold" >> profiles.yml
        echo "      threads: 4" >> profiles.yml
        echo "      keyfile: '${{ env.CREDENTIALS_FILE_PATH }}'" >> profiles.yml

    - name: Run DBT models for silver
      working-directory: ./chicago-silver
      run: |
        dbt run --target prod
    
    - name: Run DBT models for gold
      working-directory: ./chicago-gold
      run: |
        dbt run --target prod
